### ISSUE TITLE
Can't require() this package in Node.

### ISSUE THREAD

**Issue by notwaldorf** [rogerpasky/staffrender-magentaviewer#1]
If you create an empty Node project with `staffrender` as a dependency, `require('staffrender')` throws this error:
```
Error: Cannot find module 'staffrender'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```
Repro: https://glitch.com/edit/#!/magic-shrew?path=server.js:5:1

Since staffrender is a dependency of Magenta, we can no longer build the node build because of this error (and ironically, make a release to release this 😅).

**Comment by rogerpasky** [comment]
Ok. I'm hands on to solve it.

**Comment by rogerpasky** [comment]
I've been struggling for a while about this and found It is requesting the library entry point `"main": "es5/index.js"` as stated in `package.json` and there's none. This puzzles me as far as I copied almost everything in `package.json` and `webpack` from `@magenta/music` in order to make it completely compatible, so I just changed *glitch.com* code replacing `staffrender` dependence to `"@magenta/music": "1.11.2"` (forced to a previous known version without staffrender) and **it failed too**:

```
module.js:550
    throw err;
    ^
Error: Cannot find module '@magenta/music'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```
Surprisingly, it works in browsers, probably because all of them are up to date and they get the package entry point from `"module": "es6/index.js"` instead of `"main": "es5/index.js"`.

How about forcing it to `es6` ? Some advice would be more than welcome.

**Comment by rogerpasky** [comment]
Yet another choice would be forcing it to `"main": "node/index.js"` instead to `"main": "es6/index.js"` which is practically (if not absolutely) identical. I'm not sure about the implications it would have on `es5` usage. If, as I suspect, es5 is already not working, I presume there won't be any impact.

I'm going to generate a `0.2.0` staffrender version to test it. I'll let you know about the results.

**Comment by rogerpasky** [comment]
Done!

It has been created staffrender version 0.2.1 and tested in `staffrender-magentaviewer` as well as in  [https://glitch.com/edit/#!/tidy-belly?path=package.json:14:25](https://glitch.com/edit/#!/tidy-belly?path=package.json:14:25).

I don't know what side effects will have the change from `es5` to `node` in es5 demand, but remember `@magenta/music` is having exactly the same module entry point problem for es5. I guess nobody has been using `es5` version for a long time.

Even though there's no functional change, I recommend adapt `package.json` in `@magenta/music` to reference staffrender dependency to `^0.2.1`.

**Comment by notwaldorf** [comment]
Yikes, just noticed I opened this on the wrong repo (and not staffrender itself!) My bad!

I think for magenta, the es5 folder is only used to produce the one-big-library in dist/. It's a side effect that it also produces that folder, but I don't think we've ever advertised it or that anyone really uses it.

In any case: thanks so much for the fix!!

**Comment by rogerpasky** [comment]
My pleasure!
